export const USER_POST_REQUEST = 'USER_POST_REQUEST'
export const USER_POST_SUCCESS = 'USER_POST_SUCCESS'
export const USER_POST_FAILURE = 'USER_POST_FAILURE'


export const FOLLOWING_USER_POST_REQUEST = 'FOLLOWING_USER_POST_REQUEST'
export const FOLLOWING_USER_POST_SUCCESS = 'FOLLOWING_USER_POST_SUCCESS'
export const FOLLOWING_USER_POST_FAILURE = 'FOLLOWING_USER_POST_FAILURE'


export const LIKE_POST_REQUEST = 'LIKE_POST_REQUEST'
export const LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS'
export const LIKE_POST_FAILURE = 'LIKE_POST_FAILURE'